### ISSUE TITLE
Always returns Error: unauthorized

### ISSUE THREAD

**Issue by sjcliffe** [sdunster/beaconnotify#1]
Seems to be related to the addition of the Operational Yes/No question in the latest version of beacon. 

I added passing an additional "operational" variable to the POST form in lib/index.js which stopped this error but the message isn't being sent. Will need to investigate further.

**Comment by sdunster** [comment]
I tested this yesterday and didn't have a problem. Has that option been added since then?

**Comment by sjcliffe** [comment]
It was introduced in the version of beacon that went live earlier this month.

**Comment by sjcliffe** [comment]
Problem was caused by default HQ setting. It didn't have permissions for the group I was trying to send to.
